### ISSUE TITLE
[Witnessing] Witness Event is not shown in VerifyPage while being present

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/VerifyPage#29]
![image](https://user-images.githubusercontent.com/45313235/140450860-037caa16-5ed0-4058-8e93-59287823f3fd.png)

![image](https://user-images.githubusercontent.com/45313235/140450922-ade0d283-d904-4450-aa02-f6cc4ff166d0.png)

**Comment by rht** [comment]
Can't reproduce.
