### ISSUE TITLE
Extension does not work after initial installation fails with

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/VerifyPage#34]
On initial setup the extension fails (from an exported working build) based on ed5e573cc293df77bc4768aff36212a34aa5eb44

![image](https://user-images.githubusercontent.com/45313235/143143297-5c69e6b2-95ae-4e92-b8e9-3b1b53932565.png)

https://developer.chrome.com/docs/extensions/reference/scripting/#runtime-functions
it expect func as argument

this is where it happens in our code base:
https://github.com/inblockio/VerifyPage/blob/ed5e573cc293df77bc4768aff36212a34aa5eb44/src/verifier.ts#L109

Please provide more information, currently we can't reproduce.
Please provide OS and Browser names/versions.

**Comment by FantasticoFox** [comment]
He mentioned to use brave.

**Comment by 0xc0000007b** [comment]
Attempting to repro. Flying blind without more debugging info.

**Comment by 0xc0000007b** [comment]
Chromium changed from `function` to `func` last April with https://github.com/chromium/chromium/commit/1f6eb205f66d2d75b61490a2f5b74fb15c4e2825. The only public instance I can see of someone hitting this occurs in https://github.com/GoogleChrome/developer.chrome.com/issues/839 where the user hit an edge case using Brave 1.23.75 (Chromium: 90.0.4430.93) and Chrome 90.0.4430.93 and 91.0.4472.77. It may be possible to add backwards compatibility by changing `func` to `function`, though the later is a reserved word, and Chrome source code suggests `function` will be removed in the future. My suggestion is to ask the user to update their browser or, at a minimum, provide additional debugging information (OS, OS vers, Brower, Browser version).

**Comment by 0xc0000007b** [comment]
Chromium changed from `function` to `func` last April with https://github.com/chromium/chromium/commit/1f6eb205f66d2d75b61490a2f5b74fb15c4e2825. The only public instance I can see of someone hitting this occurs in https://github.com/GoogleChrome/developer.chrome.com/issues/839 where the user hit an edge case using Brave 1.23.75 (Chromium: 90.0.4430.93) and Chrome 90.0.4430.93 and 91.0.4472.77.

It may be possible to add backwards compatibility by changing `func` to `function`, though the later is a reserved word, and Chrome source code suggests `function` will be removed in the future. My suggestion is to ask the user to update their browser or, at a minimum, provide additional debugging information (OS, OS vers, Brower, Browser version).

**Comment by FantasticoFox** [comment]
Chromium stable release on Debian...
