### ISSUE TITLE
The "Verification hash matches" in the ext drop down links to ERR_FILE_NOT_FOUND page

### ISSUE THREAD

**Issue by BennSim** [inblockio/VerifyPage#37]
To recreate
-go to https://pkc.inblock.io/index.php/New_Observations_on_Jupiter
-open the extension drop down
-click on the link below
![image](https://user-images.githubusercontent.com/92349227/139382493-77f79201-f8e5-499d-84ef-b6c69bce9e82.png)
if the image is no available, click on the "Verification hash matches #" link
-page "Your file couldn’t be accessed" opens

**Comment by FantasticoFox** [comment]
Closed now. Behavior is copy with a copy box. 9610cfa11b587f12747082f9f737c88d134e286f
