### ISSUE TITLE
Users need to wait a very long time for the online-lookup to time out

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/VerifyPage#41]
![image](https://user-images.githubusercontent.com/45313235/144150801-1c3bc4d8-85fd-4d00-83b3-4c6569b63c69.png)
In case etherscan is not available, the query times are very long before timing out. 

Proposed solution: we define our own time out of max. 3 seconds per lookup.

**Comment by rht** [comment]
We use 10s instead, because even 5s is too short.
