### ISSUE TITLE
Incorrect error display when API version mismatch detected

### ISSUE THREAD

**Issue by BennSim** [inblockio/VerifyPage#43]
I downloaded the VerifyPage browser extension from the chrome store.

When I returned to my local PKC and opened the extension I see this...

![image](https://user-images.githubusercontent.com/92349227/148159048-046c28c4-d451-4e45-adc0-a4fa6ab3887a.png)

When I hit the verify page button I see this...

![image](https://user-images.githubusercontent.com/92349227/148159107-ed4b3607-1534-4575-990c-e306727d436b.png)

**Comment by rht** [comment]
Fixed in https://github.com/inblockio/VerifyPage/commit/56b5a1898dfb73656fa2c5cb3054673526eb9033.
