### ISSUE TITLE
Occasionally the cache is not updated with new verification data

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/VerifyPage#9]

**Comment by FantasticoFox** [comment]
Happens with a long revision of the 'Main Page' most likely due to some restrictions in how big the string can be which is passed to be stored in the chache.

![Selection_049](https://user-images.githubusercontent.com/45313235/132213842-b9936397-2f78-43c7-aae1-37a61421e5f0.png)

https://stackoverflow.com/questions/67552133/chrome-api-runtime-quota-bytes-per-item-quota-exceeded-error-but-precheck-pass

**Comment by FantasticoFox** [comment]
This issue occurs also in other contexts. For example, if a page has no verification data (because it was removed from the backend database) it still shows the cache data if a page with the same title exists.

**Comment by rht** [comment]
We have switched to `chrome.storage.local`, which has bigger storage. But to prevent this problem once for all, we need to switch to indexedDB.

**Comment by FantasticoFox** [comment]
Solved by changing the caching method by @rht well done!
